name: CICD
on:
  push:
    branches:
    - '*'
jobs:
  build:
    name: build flutter
    runs-on: macos-11
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.8.1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAMT_FLUTTER_2E281 }}"
          projectId: camt-flutter-2e281
          channelId: live
            - run: flutter build apk
      - run: flutter build appbundle
      - name: Archive apk artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Archive aab artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/bundlerelease/app-release.aab